#!/bin/sh

PYTHON_EXECUTABLE="python"
PYTHON_VER=`python -V 2>&1 |sed 's,Python \(.\)\..*,\1,'`
BOKKEN_DIR=`dirname $0`

if [ "$PYTHON_VER" -eq 3 ];then
    # The python executable points to Python 3.
    PYTHON_EXECUTABLE="python2"
fi

$PYTHON_EXECUTABLE $BOKKEN_DIR/bokken.py $@
