.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BOKKEN 1 "November 26, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
bokken \- RCE GUI to pyew and radare2
.SH SYNOPSIS
.B bokken
.RI [file]
.SH DESCRIPTION
This manual page documents briefly the
.B bokken
command.
.PP
\fBbokken\fP is a reverse engineering suite that using system's pyew or radare2 can help you to analyze,
dump, disassemble and visualize executable binary files (\fBPE/ELF\fP, \fBJava\fP, \fBPDF\fP) or web pages
.SH OPTIONS
Bokken can receive the target to analize as the first parameter.
.SH SEE ALSO
.BR radare2 (1).
.BR pyew (1).
.br
.SH AUTHOR
bokken was written by Hugo Teso <hugo.teso@gmail.com> and David Martínez Moreno <ender@debian.org>.
.PP
This manual page was written by David Martínez Moreno <ender@debian.org>,
for the Debian project (and may be used by others).
